In [33]:
sorted(list(chart_listener_matches))[:30]

['aj tracey',
 'amaarae',
 'anuel aa',
 'avicii',
 'bad bunny',
 'christian nodal',
 'city girls',
 'dua lipa',
 'greeicy',
 'gusttavo lima',
 'henrique & juliano',
 'iann dior',
 'iron maiden',
 'j balvin',
 'john newman',
 'jorge & mateus',
 'jt',
 'jul',
 'kali uchis',
 'lil durk',
 'lunay',
 'machine gun kelly',
 'maiara & maraisa',
 'maroon 5',
 'matisse',
 'meek mill',
 'mustard',
 'nav',
 'nick jonas',
 'omar montes']

In [32]:
chart_artist_names = set(
    charts_artists_exploded["artist_clean"].dropna()
)

chart_listener_matches = chart_artist_names.intersection(listener_artists)

len(chart_listener_matches)

42

In [31]:
charts_artists_exploded["artist_clean"] = (
    charts_artists_exploded["artist_list"]
    .str.lower()
    .str.strip()
)

charts_artists_exploded[
    ["artist_list", "artist_clean"]
].head(15)

                artist_list             artist_clean
0                Haftbefehl               haftbefehl
1                   Suchmos                  suchmos
2                  Nilipek.                 nilipek.
3                  Nilipek.                 nilipek.
4                  Nilipek.                 nilipek.
5                  Nilipek.                 nilipek.
6                    Kalido                   kalido
6             Totoy El Frio            totoy el frio
6                HIT$ MUSIC               hit$ music
7   Totova & Freddie Shuman  totova & freddie shuman
7                Begi Lotfi               begi lotfi
8                  Jay Chou                 jay chou
9                  Jay Chou                 jay chou
10                 Jay Chou                 jay chou
11                 Jay Chou                 jay chou

In [30]:
charts_artists_exploded = charts_artist_sample.explode("artist_list")

charts_artists_exploded[
    ["name", "artist_list"]
].head(15)

                  name              artist_list
0           Crackküche               Haftbefehl
1                WATER                  Suchmos
2   Gözleri Aşka Gülen                 Nilipek.
3   Gözleri Aşka Gülen                 Nilipek.
4   Gözleri Aşka Gülen                 Nilipek.
5   Gözleri Aşka Gülen                 Nilipek.
6             Opciones                   Kalido
6             Opciones            Totoy El Frio
6             Opciones               HIT$ MUSIC
7          Hosszú Idők  Totova & Freddie Shuman
7          Hosszú Idők               Begi Lotfi
8                 愛你沒差                 Jay Chou
9                 愛你沒差                 Jay Chou
10                愛你沒差                 Jay Chou
11                愛你沒差                 Jay Chou

In [29]:
import ast

charts_artist_sample["artist_list"] = charts_artist_sample["artists"].apply(
    ast.literal_eval
)

charts_artist_sample[
    ["name", "artists", "artist_list"]
].head(10)

,name,artists,artist_list
0,Crackküche,['Haftbefehl'],[Haftbefehl]
1,WATER,['Suchmos'],[Suchmos]
2,Gözleri Aşka Gülen,['Nilipek.'],[Nilipek.]
3,Gözleri Aşka Gülen,['Nilipek.'],[Nilipek.]
4,Gözleri Aşka Gülen,['Nilipek.'],[Nilipek.]
5,Gözleri Aşka Gülen,['Nilipek.'],[Nilipek.]
6,Opciones,"['Kalido', 'Totoy El Frio', 'HIT$ MUSIC']","[Kalido, Totoy El Frio, HIT$ MUSIC]"
7,Hosszú Idők,"['Totova & Freddie Shuman', 'Begi Lotfi']","[Totova & Freddie Shuman, Begi Lotfi]"
8,愛你沒差,['Jay Chou'],[Jay Chou]
9,愛你沒差,['Jay Chou'],[Jay Chou]

In [28]:
charts_artist_sample[
    charts_artist_sample["artists"].str.contains(",", na=False)
][["name", "artists"]].head(10)

                             name                                    artists
6                        Opciones  ['Kalido', 'Totoy El Frio', 'HIT$ MUSIC']
7                     Hosszú Idők  ['Totova & Freddie Shuman', 'Begi Lotfi']
424  Algo Mais (Amante) - Ao Vivo            ['Xand Avião', 'Gusttavo Lima']
425  Algo Mais (Amante) - Ao Vivo            ['Xand Avião', 'Gusttavo Lima']
426  Algo Mais (Amante) - Ao Vivo            ['Xand Avião', 'Gusttavo Lima']
427  Algo Mais (Amante) - Ao Vivo            ['Xand Avião', 'Gusttavo Lima']
428  Algo Mais (Amante) - Ao Vivo            ['Xand Avião', 'Gusttavo Lima']
429  Algo Mais (Amante) - Ao Vivo            ['Xand Avião', 'Gusttavo Lima']
430  Algo Mais (Amante) - Ao Vivo            ['Xand Avião', 'Gusttavo Lima']
431  Algo Mais (Amante) - Ao Vivo            ['Xand Avião', 'Gusttavo Lima']

In [27]:
charts_artist_sample = pd.read_csv(
    "../data/raw/charts.csv.zip",
    compression="zip",
    usecols=["name", "artists"],
    nrows=10000
)

charts_artist_sample.shape

(10000, 2)

In [26]:
charts_sample_df[
    charts_sample_df["artists"].str.contains(",", na=False)
][["name", "artists"]].head(10)

Empty DataFrame
Columns: [name, artists]
Index: []

In [25]:
sorted(list(common_artists))[:30]

['$uicideboy$',
 '(g)i-dle',
 '*nsync',
 '1nonly',
 '21 savage',
 '24kgoldn',
 '347aidan',
 '42 dugg',
 '5 seconds of summer',
 '50 cent',
 '6arelyhuman',
 '6ix9ine',
 '6ynthmane',
 'a boogie wit da hoodie',
 'a great big world',
 'a$ap ferg',
 'a$ap rocky',
 'aaron smith',
 'aastha gill',
 'acraze',
 'adele',
 'ado',
 'aerosmith',
 'aespa',
 'agroplay',
 'agust d',
 'aitch',
 'ajr',
 'akon',
 'alan walker']

In [24]:
listener_artists = set(listeners_df["Artist"].str.lower().str.strip())
spotify_artists = set(
    spotify_df["Artist"]
    .dropna()
    .str.lower()
    .str.strip()
)

common_artists = listener_artists.intersection(spotify_artists)

len(common_artists)

1003

In [23]:
spotify_df["Artist"].nunique()

1999

In [22]:
spotify_df.duplicated().sum()

np.int64(2)

In [21]:
spotify_df.isnull().sum()

Track                            0
Album Name                       0
Artist                           5
Release Date                     0
ISRC                             0
All Time Rank                    0
Track Score                      0
Spotify Streams                113
Spotify Playlist Count          70
Spotify Playlist Reach          72
Spotify Popularity             804
YouTube Views                  308
YouTube Likes                  315
TikTok Posts                  1173
TikTok Likes                   980
TikTok Views                   981
YouTube Playlist Reach        1009
Apple Music Playlist Count     561
AirPlay Spins                  498
SiriusXM Spins                2123
Deezer Playlist Count          921
Deezer Playlist Reach          928
Amazon Playlist Count         1055
Pandora Streams               1106
Pandora Track Stations        1268
Soundcloud Streams            3333
Shazam Counts                  577
TIDAL Popularity              4600
Explicit Track                   0
dtype: int64

In [20]:
spotify_df = pd.read_csv(
    "../data/raw/Most Streamed Spotify Songs 2024.csv.zip",
    compression="zip",
    encoding="latin-1"
)

spotify_df.shape

(4600, 29)

In [19]:
spotify_sample_df.dtypes

Track                             str
Album Name                        str
Artist                            str
Release Date                      str
ISRC                              str
All Time Rank                   int64
Track Score                   float64
Spotify Streams                   str
Spotify Playlist Count            str
Spotify Playlist Reach            str
Spotify Popularity              int64
YouTube Views                     str
YouTube Likes                     str
TikTok Posts                      str
TikTok Likes                      str
TikTok Views                      str
YouTube Playlist Reach            str
Apple Music Playlist Count      int64
AirPlay Spins                     str
SiriusXM Spins                    str
Deezer Playlist Count           int64
Deezer Playlist Reach             str
Amazon Playlist Count           int64
Pandora Streams                   str
Pandora Track Stations            str
Soundcloud Streams                str
Shazam Counts                     str
TIDAL Popularity              float64
Explicit Track                  int64
dtype: object

In [18]:
spotify_sample_df.columns.tolist()

['Track',
 'Album Name',
 'Artist',
 'Release Date',
 'ISRC',
 'All Time Rank',
 'Track Score',
 'Spotify Streams',
 'Spotify Playlist Count',
 'Spotify Playlist Reach',
 'Spotify Popularity',
 'YouTube Views',
 'YouTube Likes',
 'TikTok Posts',
 'TikTok Likes',
 'TikTok Views',
 'YouTube Playlist Reach',
 'Apple Music Playlist Count',
 'AirPlay Spins',
 'SiriusXM Spins',
 'Deezer Playlist Count',
 'Deezer Playlist Reach',
 'Amazon Playlist Count',
 'Pandora Streams',
 'Pandora Track Stations',
 'Soundcloud Streams',
 'Shazam Counts',
 'TIDAL Popularity',
 'Explicit Track']

In [17]:
spotify_sample_df = pd.read_csv(
    "../data/raw/Most Streamed Spotify Songs 2024.csv.zip",
    compression="zip",
    encoding="latin-1",
    nrows=5
)

spotify_sample_df

,Track,Album Name,Artist,Release Date,ISRC,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,...,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Soundcloud Streams,Shazam Counts,TIDAL Popularity,Explicit Track
0,MILLION DOLLAR BABY,Million Dollar Baby - Single,Tommy Richman,4/26/2024,QM24S2402528,1,725.4,"390,470,936","30,716","196,631,588",...,684,62,"17,598,718",114,"18,004,655","22,931","4,818,457","2,669,262",NaN,0
1,Not Like Us,Not Like Us,Kendrick Lamar,5/4/2024,USUG12400910,2,545.9,"323,703,884","28,113","174,597,137",...,3,67,"10,422,430",111,"7,780,028","28,444","6,623,075","1,118,279",NaN,1
2,i like the way you kiss me,I like the way you kiss me,Artemas,3/19/2024,QZJ842400387,3,538.4,"601,309,283","54,331","211,607,669",...,536,136,"36,321,847",172,"5,022,621","5,639","7,208,651","5,285,340",NaN,0
3,Flowers,Flowers - Single,Miley Cyrus,1/12/2023,USSM12209777,4,444.9,"2,031,280,633","269,802","136,569,078",...,"2,182",264,"24,684,248",210,"190,260,277","203,384",NaN,"11,822,942",NaN,0
4,Houdini,Houdini,Eminem,5/31/2024,USUG12403398,5,423.3,"107,034,922","7,223","151,469,874",...,1,82,"17,660,624",105,"4,493,884","7,006","207,179","457,017",NaN,1

In [16]:
import zipfile

with zipfile.ZipFile(
    "../data/raw/Most Streamed Spotify Songs 2024.csv.zip",
    "r"
) as zip_file:

    with zip_file.open("Most Streamed Spotify Songs 2024.csv") as csv_file:
        raw_sample = csv_file.read(5000)

raw_sample[:200]

b'Track,Album Name,Artist,Release Date,ISRC,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,Spotify Popularity,YouTube Views,YouTube Likes,TikTok Posts,TikTok Lik'

In [15]:
spotify_sample_df = pd.read_csv(
    "../data/raw/Most Streamed Spotify Songs 2024.csv.zip",
    compression="zip",
    nrows=5
)

spotify_sample_df

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 2679: invalid start byte

In [14]:
with zipfile.ZipFile(
    "../data/raw/Most Streamed Spotify Songs 2024.csv.zip",
    "r"
) as zip_file:
    print(zip_file.namelist())

['Most Streamed Spotify Songs 2024.csv']

In [13]:
row_count = 0

for chunk in pd.read_csv(
    "../data/raw/charts.csv.zip",
    compression="zip",
    chunksize=100000
):
    row_count += len(chunk)

row_count

5428021

In [12]:
charts_sample_df.dtypes

date               str
country            str
position         int64
streams          int64
track_id           str
artists            str
artist_genres      str
duration         int64
explicit          bool
name               str
dtype: object

In [11]:
charts_sample_df.columns.tolist()

['date',
 'country',
 'position',
 'streams',
 'track_id',
 'artists',
 'artist_genres',
 'duration',
 'explicit',
 'name']

In [10]:
charts_sample_df = pd.read_csv(
    "../data/raw/charts.csv.zip",
    compression="zip",
    nrows=5
)

charts_sample_df

,date,country,position,streams,track_id,artists,artist_genres,duration,explicit,name
0,2021/04/15,de,82,625718,20IvMlpi4U5RuDnAlXSRiV,['Haftbefehl'],['german hip hop'],198746,False,Crackküche
1,2019/01/31,jp,171,50896,0V1K6MU0utODk4yNqZKsFv,['Suchmos'],"['japanese r&b', 'j-rock', 'japanese soul', 'j...",408320,False,WATER
2,2018/11/15,tr,59,185439,4qzZm5EIdFurBpDieEmVc9,['Nilipek.'],"['turkish singer-songwriter', 'turkish rock']",257142,False,Gözleri Aşka Gülen
3,2018/11/22,tr,133,111159,4qzZm5EIdFurBpDieEmVc9,['Nilipek.'],"['turkish singer-songwriter', 'turkish rock']",257142,False,Gözleri Aşka Gülen
4,2018/11/29,tr,166,96204,4qzZm5EIdFurBpDieEmVc9,['Nilipek.'],"['turkish singer-songwriter', 'turkish rock']",257142,False,Gözleri Aşka Gülen

In [9]:
import zipfile

with zipfile.ZipFile("../data/raw/charts.csv.zip", "r") as zip_file:
    print(zip_file.namelist())

['charts.csv']

In [8]:
import os

os.listdir("../data/raw")

['charts.csv.zip', 'Most Streamed Spotify Songs 2024.csv.zip', 'listeners.csv']

In [7]:
listeners_df.duplicated().sum()

np.int64(0)

In [6]:
listeners_df.isnull().sum()

Artist         0
Listeners      0
Daily Trend    0
Peak           0
PkListeners    0
dtype: int64

In [5]:
listeners_df.dtypes

Artist           str
Listeners        str
Daily Trend      str
Peak           int64
PkListeners      str
dtype: object

In [4]:
listeners_df.shape

(2500, 5)

In [3]:
listeners_df.head()

         Artist    Listeners Daily Trend  Peak  PkListeners
0    The Weeknd  107,592,328    -138,880     1  113,034,886
1  Taylor Swift  101,003,302         889     2  101,003,302
2    Ed Sheeran   76,475,126     -68,137     2   87,934,910
3      Dua Lipa   76,421,916     -71,356     4   77,778,397
4     Bad Bunny   76,162,057    -199,052     3   83,950,570

In [2]:
listeners_df = pd.read_csv("../data/raw/listeners.csv")

In [1]:
import pandas as pd